name: Python Dependency Caching CI

on:
  # Triggers the workflow on push or manually
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      # Install the same Python version used in your Dockerfile for consistency
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        # Assign an ID to this step to retrieve version info if needed
        id: setup-python

    # --- Cache Step Definition ---
    # Prime the cache with a key based on the specific required prefix and the hash of requirements.txt
    - name: Prime cache-6b79bc5 (Cache Dependencies)
      # CHANGED: Setting the ID to the required reference name to fix the 'No workflow step' error.
      id: prime-cache-6b79bc5 
      uses: actions/cache@v4
      with:
        # Cache the location where pip stores downloaded packages
        path: ~/.cache/pip
        # Use the specific key prefix, combined with OS, Python version, and requirements hash
        key: cache-6b79bc5-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('requirements.txt') }}
        # Fallback keys to use if the exact key doesn't match
        restore-keys: |
          cache-6b79bc5-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-
          cache-6b79bc5-${{ runner.os }}-

    # --- Status Reporting Step ---
    - name: Echo Cache Status
      # CHANGED: The step below now correctly references the updated ID: prime-cache-6b79bc5
      run: |
        echo "--- Cache Status ---"
        echo "Cache result for cache-6b79bc5: ${{ steps.prime-cache-6b79bc5.outputs.cache-hit }}"
        # Output: "true" means dependencies were restored from cache (faster build)
        # Output: "false" means dependencies need to be installed (slower build, cache saved afterwards)

    # --- Dependency Installation ---
    - name: Install dependencies from requirements.txt
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run linting/tests (Placeholder)
      run: echo "CI pipeline complete."
